from __future__ import annotations

import csv
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

INVENTORY_CSV = (
    ROOT
    / "docs"
    / "legacy_analysis_inventory_review.csv"
)

OUTPUT_MD = (
    ROOT
    / "docs"
    / "legacy_version_conflicts.md"
)


def load_rows() -> list[dict[str, str]]:
    with INVENTORY_CSV.open(
        "r",
        encoding="utf-8-sig",
        newline="",
    ) as handle:
        return list(
            csv.DictReader(handle)
        )


def main() -> None:
    rows = load_rows()

    groups: dict[
        str,
        list[dict[str, str]],
    ] = defaultdict(list)

    for row in rows:
        number = row.get(
            "script_number",
            "",
        ).strip()

        if number:
            groups[number].append(row)

    duplicates = {
        number: group
        for number, group in groups.items()
        if len(group) > 1
    }

    lines = [
        "# Legacy Script Version Conflicts",
        "",
        (
            "This report lists numeric script IDs "
            "represented by multiple source files."
        ),
        "",
        (
            "No version is considered authoritative "
            "until reviewed against the scientific history "
            "and locked outputs."
        ),
        "",
    ]

    if not duplicates:
        lines.append(
            "No duplicate numeric script IDs detected."
        )

    for number in sorted(
        duplicates,
        key=int,
    ):
        lines.extend(
            [
                f"## Script {number}",
                "",
            ]
        )

        for row in duplicates[number]:
            lines.extend(
                [
                    f"### `{row['filename']}`",
                    "",
                    (
                        f"- Declared version: "
                        f"`{row['declared_version']}`"
                    ),
                    (
                        f"- SHA-256: "
                        f"`{row['sha256']}`"
                    ),
                    (
                        f"- Last Git commit: "
                        f"`{row['last_git_commit']}`"
                    ),
                    (
                        f"- Commit date: "
                        f"`{row['last_git_commit_date']}`"
                    ),
                    (
                        f"- Commit subject: "
                        f"{row['last_git_commit_subject']}"
                    ),
                    (
                        f"- Randomization detected: "
                        f"{row['randomization_detected']}"
                    ),
                    (
                        f"- Seed literals: "
                        f"`{row['seed_literals']}`"
                    ),
                    (
                        f"- Lock markers: "
                        f"`{row['lock_markers']}`"
                    ),
                    "",
                ]
            )

        lines.extend(
            [
                "### Manual decision",
                "",
                "- Authoritative file: **TBD**",
                "- Superseded file(s): **TBD**",
                "- Evidence for decision: **TBD**",
                "- Locked outputs generated by authoritative file: **TBD**",
                "",
            ]
        )

    OUTPUT_MD.write_text(
        "\n".join(lines),
        encoding="utf-8",
    )

    print(
        f"Duplicate script groups: "
        f"{len(duplicates)}"
    )

    for number in sorted(
        duplicates,
        key=int,
    ):
        filenames = [
            row["filename"]
            for row in duplicates[number]
        ]

        print(
            f"  {number}: "
            + " | ".join(filenames)
        )

    print()
    print(
        f"Written: "
        f"{OUTPUT_MD.relative_to(ROOT)}"
    )


if __name__ == "__main__":
    main()
